meta-integrity: Fix failure to find linux-yocto-integrity.inc
Issue: LIN1022-2631

linux-yocto-integrity.inc is shared among linux-yocto linux-yocto-rt and
linux-yocto-dev and cannot be found with ${BPN} in the latter two.

ERROR: ParseError at layers/meta-secure-core/meta-integrity/recipes-kernel/linux/linux-yocto-dev.bbappend:1:
Could not include required file linux-yocto-dev-integrity.inc
ERROR: ParseError at layers/meta-secure-core/meta-integrity/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend:1:
Could not include required file linux-yocto-rt-integrity.inc

(LOCAL REV: NOT UPSTREAM) -- Sent to github meta-secure-core on 20221208
https://github.com/jiazhang0/meta-secure-core/pull/258

Signed-off-by: He Zhe <zhe.he@windriver.com>