meta-tpm2: check the tpm2 DISTRO_FEATURES
Issue: LINUXEXEC-23251

Fix the below yocto compliance issue:
  INFO: test_signatures (common.CommonCheckLayer)
  INFO:  ... FAIL

  Stdout:
  Loading cache...done.
  Loaded 1645 entries from dependency cache.
  INFO: Traceback (most recent call last):
   File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 81, in test_signatures
    self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
AssertionError: Adding layer meta-tpm2 changed signatures.
107 signatures changed, initial differences (first hash before, second after):
   linux-yocto:do_fetch: c57d21fe3def6c9959bbfd487420c6845d4c720d7e72aa5cf1e11af324ba5d45 -> 3b1f37d37a491287fa36bc0f1e3d65d6ff2af899d173f684600a8fbff643b695
      bitbake-diffsigs --task linux-yocto do_fetch --signature c57d21fe3def6c9959bbfd487420c6845d4c720d7e72aa5cf1e11af324ba5d45 3b1f37d37a491287fa36bc0f1e3d65d6ff2af899d173f684600a8fbff643b695
      NOTE: Starting bitbake server...
      basehash changed from 847e3bff305906a9ad386dc76de2fc2dfdaf7bc2b7dfb15bb2cd17dd9ba1f8bd to a522d659617359c730eac2f149a171ddd030959af67d1d3c3606cc9adba7db08
      Variable SRC_URI value changed:
      @@ -1 +1,2 @@
      -git://git.yoctoproject.org/linux-yocto.git;name=machine;branch=${KBRANCH};            git://git.yoctoproject.org/yocto-kernel-cache;type=kmeta;name=meta;branch=yocto-5.15;destsuffix=${KMETA}
      +git://git.yoctoproject.org/linux-yocto.git;name=machine;branch=${KBRANCH};            git://git.yoctoproject.org/yocto-kernel-cache;type=kmeta;name=meta;branch=yocto-5.15;destsuffix=${KMETA}     ${@bb.utils.contains('DISTRO_FEATURES', 'tpm2',                          'file://tpm2.scc file://tpm2.cfg', '', d)}
      +DISTRO_FEATURES{tpm2} = Unset

(LOCAL REV: NOT UPSTREAM) -- Sent to github on 20221129

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>